name: centos8
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '! ci/**.md'
  pull_request:
    paths-ignore:
      - '**.md'
      - '! ci/**.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: tgagor/centos:stream8
    timeout-minutes: 10
    strategy:
      matrix:
        module:
          - name: AdocMan.cmake
            ci: adocman
          - name: FindOpenSSLFeatures.cmake
            ci: findossl
          - name: PandocMan.cmake
            ci: pandocman
          - name: FindBotan.cmake
            ci: findbotan
      fail-fast: false
    name: Check CMake module
    steps:
      - run: |
          dnf -y install git
      - uses: actions/checkout@v3
      - name: Install needed packages
        run: |
          set -eux
          dnf -y -q install sudo wget
          sudo dnf -y -q install clang llvm gcc gcc-c++ make autoconf automake libtool gzip ncurses-devel byacc gettext-devel bison cmake ruby-devel
          sudo dnf -y -q install epel-release && \
          sudo dnf -y -q install 'dnf-command(config-manager)' && \
          sudo dnf config-manager --set-enabled powertools
          sudo dnf -y -q install openssl-devel
      - name: Check FindOpenSSLFeatures.cmake
        if: matrix.module.name == 'FindOpenSSLFeatures.cmake'
        run: |
          set -eux
          mkdir "${GITHUB_WORKSPACE}/build"
          pushd "${GITHUB_WORKSPACE}/build"
          cmake "${GITHUB_WORKSPACE}/ci/findossl" "-DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE}"
          cmake --build .
          popd
      - name: Check AdocMan.cmake
        if: matrix.module.name == 'AdocMan.cmake'
        run: |
          set -eux
          sudo gem install asciidoctor
          sudo dnf -y -q install man
          mkdir "${GITHUB_WORKSPACE}/build"
          pushd "${GITHUB_WORKSPACE}/build"
          cmake "${GITHUB_WORKSPACE}/ci/adocman" "-DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE}"
          cmake --build .
          cmake --install .
          [ -f testadoc.1 ]
          man ./testadoc.1
          man testadoc
          popd
      - name: Check PandocMan.cmake
        if: matrix.module.name == 'PandocMan.cmake'
        run: |
          set -eux
          sudo dnf -y -q install pandoc
          mkdir "${GITHUB_WORKSPACE}/build"
          pushd "${GITHUB_WORKSPACE}/build"
          cmake "${GITHUB_WORKSPACE}/ci/pandocman" "-DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE}"
          cmake --build .
          cmake --install .
          [ -f testpandoc.1 ]
          man ./testpandoc.1
          man testpandoc
          popd
      - name: Check FindBotan.cmake
        if: matrix.module.name == 'FindBotan.cmake'
        run: |
          set -eux
          sudo dnf -y -q install python3-devel
          git clone --depth 1 --branch 2.19.3 https://github.com/randombit/botan.git
          pushd botan
          python3 configure.py && make -j2 && make -j2 install
          popd
          mkdir "${GITHUB_WORKSPACE}/build"
          pushd "${GITHUB_WORKSPACE}/build"
          cmake "${GITHUB_WORKSPACE}/ci/findbotan" "-DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE}"
          grep -q "/usr/local/lib/libbotan-2.so" "${GITHUB_WORKSPACE}/ci/findbotan/findbotan.txt"
          grep -q "/usr/local/include/botan-2" "${GITHUB_WORKSPACE}/ci/findbotan/findbotan.txt"
          popd

